<p>Mikołaj Roszak Przedwiośnie 79/12 73-110 Stargard Tel. +48 500487977 Skype: mikolajroszak_1 Email: <a href="mailto:ul.echo12@gmail.com">ul.echo12@gmail.com</a>&nbsp;<a href="http://www.mikolaj.com" target="_blank" rel="noopener" title="mikolaj.com">http://www.mikolaj.com</a></p>
<p></p>
<p>&nbsp;</p>
Mikołaj Roszak
Przedwiośnie 79/12
73-110 Stargard
Web: www.mikolaj.com
email me: ul.echo12@gmail.com
mikolaj@mikolaj.com
skype: mikolajroszak_1
Tel. +48 500 487 977977

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true
